server:
  port: 7001

spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
    name: springboot
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/shop?characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity